"""linhas de produto tabacaria

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-08 11:35:27.406029
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_line', sa.String(length=20), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_key', sa.String(length=80), server_default='', nullable=False))
        batch_op.add_column(sa.Column('product_line', sa.String(length=20), server_default='energetico', nullable=False))
        batch_op.alter_column('idempotency_key',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_orders_checkout_key'), ['checkout_key'], unique=False)

    with op.batch_alter_table('price_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_line', sa.String(length=20), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line', sa.String(length=20), server_default='energetico', nullable=False))
        batch_op.add_column(sa.Column('sale_unit', sa.String(length=20), server_default='caixa', nullable=False))
        batch_op.add_column(sa.Column('pack_contents', sa.Integer(), nullable=True))

    # ### end Alembic commands ###
    # Dados existentes: tudo era energético.
    op.execute("UPDATE orders SET checkout_key = idempotency_key WHERE checkout_key = ''")
    op.execute("UPDATE price_rules SET product_line = 'energetico' WHERE product_id IS NULL AND customer_id IS NULL AND channel IS NULL AND product_line IS NULL")
    op.execute("UPDATE campaigns SET product_line = 'energetico' WHERE product_line IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('pack_contents')
        batch_op.drop_column('sale_unit')
        batch_op.drop_column('line')

    with op.batch_alter_table('price_rules', schema=None) as batch_op:
        batch_op.drop_column('product_line')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_checkout_key'))
        batch_op.alter_column('idempotency_key',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('product_line')
        batch_op.drop_column('checkout_key')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('product_line')

    # ### end Alembic commands ###
